# Generated by Django 3.2 on 2023-07-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('creation_datetime', models.DateTimeField()),
                ('bucket', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-creation_datetime'],
            },
        ),
        migrations.CreateModel(
            name='IngestionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'ok'), ('ko', 'ko')], max_length=10, verbose_name='status')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
                ('ingestion_timestamp', models.DateTimeField(auto_now_add=True, verbose_name="temps d'ingestion")),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.file', verbose_name='nom du fichier')),
            ],
            options={
                'ordering': ['-ingestion_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="nom d'utilisateur")),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('description', models.TextField(verbose_name='texte de description')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse mail')),
                ('ingestion_datetime', models.DateTimeField(auto_now_add=True, verbose_name="temps d'ingestion")),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.file', verbose_name='nom du fichier')),
            ],
        ),
    ]
