# Generated by Django 3.2 on 2023-06-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='address',
            field=models.CharField(max_length=255, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='description',
            field=models.TextField(verbose_name='Texte de description'),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Une adresse mail'),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='username',
            field=models.CharField(max_length=255, verbose_name="nom d'utilisateur"),
        ),
    ]
