# Generated by Django 3.2 on 2023-06-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230625_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='file_name',
            field=models.CharField(default='cb-silver-bucket/csv-data/sample.csv', max_length=255, verbose_name='nom du fichier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='description',
            field=models.TextField(verbose_name='texte de description'),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='adresse mail'),
        ),
    ]
