# Generated by Django 3.2 on 2023-06-26 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230626_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
